name: civil_eng_tools_pro
description: A new Flutter project for Civil Engineering Tools.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0 # For Noto Sans and Plus Jakarta Sans
  font_awesome_flutter: ^10.7.0 # For FontAwesome icons
  cupertino_icons: ^1.0.2
  file_picker: ^8.0.0 # For picking files
  flutter_dropzone: ^4.2.1 # For drag and drop file functionality
  http: ^1.2.1 # For making HTTP requests
  supabase_flutter: ^2.5.0 # Supabase client for Flutter
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true 